# Generated by Django 5.1.1 on 2024-10-04 12:43

import todo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todolist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.DateTimeField(blank=True, default=todo_app.models.TodoList.get_deadline, null=True),
        ),
    ]
