# Generated by Django 5.1.1 on 2024-10-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0003_alter_todolist_deadline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todolist",
            old_name="created_at",
            new_name="created",
        ),
    ]
